name: genomics-data-mining
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - ipykernel
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - ydata-profiling
  - itables
  - ipywidgets
  - setuptools<=81
  - openlineage-python
  - cbioportal
prefix: .\env